version: '3'

services:

  app:
    build: 
      context: './src/app'
      dockerfile: 'Dockerfile.app'
    volumes:
      - './src/app:/app'
      - './dist:/dist'

  www:
    image: tmvdl/projects:app
    build: 
      context: './src/app'
      dockerfile: 'Dockerfile.www'
    volumes:
      - './src/app:/app'
      - './dist:/dist'
    ports:
      -  '80:80'
