name: Docker Hub

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: tmvdl
          password: ${{ secrets.GITHUBDOCKER }}

      - name: Build www
        run: docker-compose build www 

      - name: Push
        run: docker push tmvdl/projects:app

