name: Github Artifacts

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Build app
        run: docker-compose up

      - name: Export app
        run: docker run -v $(pwd)/dist:/dist -w /dist app_app cp /app/hello/platforms/android/app/build/outputs/apk/debug/app-debug.apk . 

      - name: Create release
        run: gh release create v$( date +%Y%m%d%H%M ) ./dist/*.apk
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
