name: APK on Github Artifacts

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Build Android
        run: docker-compose build app

      - name: Build Android
        run: ls -la build

      # - name: Create release
      #   run: gh release create v$( date +%Y%m%d ) ./build/*.apk
      #   env:
      #       GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
