name: APK on Github Artifacts

on:
  workflow_dispatch:
  push:
    branches: 
      - 'main'

jobs:
  artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Build .apk
        uses: brtmvdl/apk
        env:
            PATH: ./src/www
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
