name: Github Artifacts

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Build app
        run: docker-compose build app

      - name: Create release
        run: gh release create v$( date +%Y%m%d ) ./src/app/hello/platforms/android/app/build/outputs/apk/debug/*.apk
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
