name: APK on Github Artifacts

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Build Android
        run: bash ./env/build.sh

      # - name: Create release
      #   run: gh release create v$( date +%Y%m%d ) ./src/app/platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
      #   env:
      #       GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
