name: APK on Github Artifacts

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Create project
        run: docker-compose -f ./docker-compose.yaml run app ionic init hello --type=custom --project-id=com.example.hello

      - name: Create an Android project
        run: docker-compose -f ./docker-compose.yaml run app cordova create hello com.example.hello hello

      - name: Init the project
        run: docker-compose -f ./docker-compose.yaml run app npm init -y

      - name: Enable cordova
        run: docker-compose -f ./docker-compose.yaml run app ionic integrations enable cordova --add --confirm --prod --no-interactive --noresources

      - name: Install packages
        run: docker-compose -f ./docker-compose.yaml run app npm i

      - name: Add Android platform
        run: docker-compose -f ./docker-compose.yaml run app ionic cordova platform add android --confirm

      - name: Build .apk file
        run: docker-compose -f ./docker-compose.yaml run app ionic cordova build android --release --prod --no-interactive --device --confirm --prod --no-interactive --noresources

      # - name: Create release
      #   run: gh release create v$( date +%Y%m%d ) ./src/app/platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
      #   env:
      #       GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
